apiVersion: v1
kind: Service
metadata:
  name: salesloft-proxy
spec:
  selector:
    app: salesloft-proxy
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: LoadBalancer
